name: shell command
on : push

jobs:
  run-shell-command:
   runs-on: ubuntu-latest
   steps :
   - name : String
     run : echo "Hello World"
   -  name : Multiline
      run : |
       node -v
       npm -v 
   -  name: Simple JS action
      id : greet
      uses: HarikiranGit/repo-1@44f161132310341e3a43243e779aa41f3104a3d4
      with:
       who-to-greet: John
   - name: log greet time
     run: echo "${{steps.greet.outputs.time}}"
